### ISSUE TITLE
Downward compatibility?

### ISSUE THREAD

**Issue by sigmaroot** [ShepherdJerred/sthorses#12]
After a update to the new 1.11 stHorses update, players aren't able to place old stored horses.

That's not good, a plugin should always contain a downward compatibility for some versions.

Any ideas how to solve this? We have many players and they don't want to loose all of the horses!

**Comment by sigmaroot** [comment]
You may have a look on my dev-1 branch:

[https://github.com/sigmaroot/stHorses/tree/dev-1](stHorses dev-1 branch)

**Comment by ShepherdJerred** [comment]
As always thank you for the help! Your commit looks like it should work properly with old horses, I'll merge it and post an update.
