### ISSUE TITLE
Wrong carpet color restored

### ISSUE THREAD

**Issue by sigmaroot** [ShepherdJerred/sthorses#16]
At the moment, the carpet color is not saved and only a white carpet is restored.

As I can see, you have a TODO in the code. I've done that for you 😄 
I'm going to request a pull.

**Comment by ShepherdJerred** [comment]
I'd rather store the color in the item itself, not in the lore. Thanks for the help though!

**Comment by sigmaroot** [comment]
I've stored it now in both ways. As lore and item data.

**Comment by ShepherdJerred** [comment]
Ah, great!

**Comment by ShepherdJerred** [comment]
A build with all your changes can be found here https://ts-mc.net/jenkins/job/sthorses/17/

**Comment by sigmaroot** [comment]
Thanks, I'm running my own dev build from maven (local repo) 😁
