### ISSUE TITLE
stHorses - Perms don't work

### ISSUE THREAD

**Issue by Metisuneatn** [ShepherdJerred/sthorses#5]
The perms for stHorses doesnt work with PEX. I have it to where players have to earn a rank and on one of the ranks they can use the saddles on the horses. However... well everyone can do it.

**Comment by ShepherdJerred** [comment]
Did you negate the permission for those you didn't want to be able to use the features?

**Comment by Metisuneatn** [comment]
Plugin ignores permissions all together.

**Comment by Metisuneatn** [comment]
If your closing this why did you even reply?

**Comment by ShepherdJerred** [comment]
I'm not.

**Comment by ShepherdJerred** [comment]
Try with the latest release. The plugin does check for permissions.
